dependencies:
  flutter:
    sdk: flutter

  # البوصلة والحساسات
  flutter_compass: ^0.8.0
  sensors_plus: ^6.0.0

  # الموقع والإحداثيات
  geolocator: ^12.0.0
  latlong2: ^0.9.1

  # الخرائط بدون إنترنت
  flutter_map: ^7.0.0

  # AR والكاميرا والفلاش
  camera: ^0.11.0
  torch_light: ^1.0.0

  # اهتزاز الجهاز
  vibration: ^2.0.0
  
